### ISSUE TITLE
Add timestamp to available update!

### ISSUE THREAD

**Issue by mostaphaRoudsari** [didimitrie/SpeckleGrasshopper#10]
The "There is an update" warning is very nice. I think adding a timestamp can make it even better so I get something like: `There is an update available from 10/19/2017 at 3:03 EST`

**Comment by didimitrie** [comment]
Yes, this is a super good shout (and easy to do too, hehe 👍 )

**Comment by didimitrie** [comment]
Finally closed in https://github.com/speckleworks/SpeckleGrasshopper/commit/dd83a5ee83019e2d79e52dc7e0e6391b6ca62fb7!
